version: "3"
services:
  postgres:
    container_name: nikhil_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /Users/admin/projects/data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - krunal

networks:
  krunal:
    driver: bridge
